PAD_WORD = '[PAD]'
PAD=0
CLS_WORD = '[CLS]'
CLS =1
UNK_WORD = '[UNK]'
UNK = 2
SEP_WORD = '[SEP]'
SEP = 3
LINESEP_WORD = '</s>'
LINESEP=4

id2vocab=dict({PAD:PAD_WORD, CLS:CLS_WORD, UNK:UNK_WORD, SEP:SEP_WORD, LINESEP:LINESEP_WORD})
vocab2id=dict({PAD_WORD:PAD, CLS_WORD:CLS, UNK_WORD:UNK, SEP_WORD:SEP, LINESEP_WORD:LINESEP})

